
project_id = "pcnrnciwgdrukzciwexi"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
email_confirm_url = "http://localhost:3000"

[db]
enabled = true
port = 54322
shadow_port = 54320

[functions]
enabled = true
port = 54321

[functions.get-auth-users]
verify_jwt = true

[realtime]
enabled = true
port = 54323

[storage]
enabled = true
port = 54324

[analytics]
enabled = false
