// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcnrnciwgdrukzciwexi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjbnJuY2l3Z2RydWt6Y2l3ZXhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NDAyMDEsImV4cCI6MjA2MTMxNjIwMX0.3IcY8LAe71hLlYQ7ZzkABWEQUiqiv98Tu-IiCbxGPr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
